/**
 * ENTROPY — the root of Veyra's security.
 *
 * ─── What is it? ───────────────────────────────────────────────────────────
 * Entropy is a measure of unpredictability. A 128-bit random value has 128
 * bits of entropy if, and only if, an adversary who knows everything about
 * the *process* that produced it still has 2^128 equally-likely candidates.
 *
 * ─── Why is it necessary? ──────────────────────────────────────────────────
 * Every other guarantee in this wallet is downstream of this file.
 *
 *     entropy → seed → master key → child keys → addresses → your money
 *
 * secp256k1's discrete-log hardness protects a key that was *sampled
 * uniformly*. It offers nothing at all against a key that was drawn from a
 * small or predictable set. An attacker does not need to break the curve if
 * he can simply enumerate the 2^32 outputs of a badly-seeded PRNG. This has
 * happened repeatedly in the real world:
 *
 *   - Android SecureRandom (2013): a broken PRNG on Android produced
 *     repeated ECDSA nonces, letting attackers recover private keys from
 *     on-chain signatures and drain wallets.
 *   - Debian OpenSSL (2006–2008): a patch reduced the effective seed space
 *     to ~32,768 values. Every key generated on affected systems for two
 *     years was enumerable.
 *   - "Brainwallets": keys derived from human-chosen passphrases. Attackers
 *     run dictionary sweeps and empty them within seconds of funding.
 *
 * The lesson is consistent: the curve is never the weak point. The sampler is.
 *
 * ─── How does it work here? ────────────────────────────────────────────────
 * We do not invent a random number generator. We delegate to the operating
 * system's CSPRNG via the Web Crypto API (`crypto.getRandomValues`), which in
 * Node maps to the same kernel source as `/dev/urandom` (getrandom(2) on
 * Linux, BCryptGenRandom on Windows, CCRandomGenerateBytes on macOS). The OS
 * generator is continuously reseeded from hardware and kernel event noise,
 * and is designed to be forward- and backward-secure even if some internal
 * state is later exposed.
 *
 * ─── What mathematical principle does it depend on? ────────────────────────
 * None, strictly. This is the one part of the stack that rests on a *systems*
 * assumption rather than a mathematical one: that the host OS CSPRNG is
 * properly seeded and unbroken. That assumption is recorded explicitly in
 * docs/THREAT-MODEL.md, because it is the single most load-bearing
 * non-mathematical assumption Veyra makes.
 *
 * ─── What happens if it is implemented incorrectly? ────────────────────────
 * Total, silent, unrecoverable compromise. Note the word *silent*: a wallet
 * built on weak entropy behaves perfectly. It generates addresses, receives
 * coins, signs valid transactions. There is no test you can run against the
 * wallet's own output that reveals the flaw, because the output is
 * structurally correct — it is only the *distribution* that is wrong. This is
 * why the guard tests in tests/cryptography/ inspect the source tree itself
 * rather than only the values produced.
 *
 * ─── How could an attacker attack it? ──────────────────────────────────────
 *   - Supply-chain: replace this module, or shim `globalThis.crypto`, so it
 *     returns attacker-chosen bytes. Mitigation is dependency auditing and
 *     the fact that this file has zero third-party imports.
 *   - Fault/VM-reset: force the host to reuse RNG state across VM snapshots.
 *   - Side channel: observe timing or memory to recover generated bytes.
 */

import { EntropyUnavailableError, EntropyInsufficientError } from "../errors/index.js";

/**
 * Minimum entropy Veyra will produce, in bytes.
 *
 * 128 bits. Why not less? BIP-39 permits 128-bit entropy (12 words) and that
 * is the floor the ecosystem has settled on. Why not demand 256 everywhere?
 * Because secp256k1 itself only offers ~128 bits of security against generic
 * discrete-log attacks (Pollard's rho runs in ~sqrt(n) ≈ 2^128 for a 256-bit
 * group order). Entropy beyond 128 bits does not buy additional protection
 * against the strongest known attack on the curve, so 128 is the honest
 * minimum and 256 is the conservative default.
 */
export const MIN_ENTROPY_BYTES = 16;

/** Default entropy size: 256 bits — matches a 24-word BIP-39 mnemonic. */
export const DEFAULT_ENTROPY_BYTES = 32;

/**
 * Largest single draw we permit. Not a security limit — a sanity limit, so a
 * caller bug (e.g. an unvalidated length from an API request) cannot turn
 * into a memory-exhaustion denial of service.
 */
export const MAX_ENTROPY_BYTES = 1024;

/**
 * A pluggable random source.
 *
 * This exists for ONE reason: so that tests can inject a *known-bad* source
 * and assert that downstream code still behaves correctly (for example, that
 * private-key rejection sampling correctly discards an out-of-range scalar).
 *
 * It is deliberately NOT a general configuration hook. Nothing in the wallet,
 * the API, or the UI may pass a custom source. Production code paths call
 * `randomBytes()` with no argument, which always reaches the OS CSPRNG.
 * See tests/cryptography/entropy.test.ts for the guard that enforces this.
 */
export type RandomSource = (out: Uint8Array) => void;

/**
 * Resolve the platform CSPRNG.
 *
 * We reach for `globalThis.crypto.getRandomValues` rather than importing
 * `node:crypto`, because it is the one API that exists identically in Node
 * (>=19 globally), Deno, Bun, browsers, and React Native with a polyfill.
 * The core must not be tied to a Node-only import: core/ has to run in the
 * same form inside the eventual mobile UI.
 *
 * If it is absent we throw. We never fall back to anything. A fallback here
 * is exactly how the historical disasters listed above happened: some code
 * path quietly degraded to a weaker source and nobody noticed.
 */
function platformRandom(): RandomSource {
  const webcrypto = (globalThis as {
    crypto?: { getRandomValues?: <T extends ArrayBufferView>(array: T) => T };
  }).crypto;
  const getRandomValues = webcrypto?.getRandomValues;
  if (typeof getRandomValues !== "function") {
    throw new EntropyUnavailableError();
  }
  return (out: Uint8Array) => {
    // getRandomValues is capped at 65536 bytes per call by the spec.
    // MAX_ENTROPY_BYTES keeps us well under that, but we fill in chunks
    // anyway so the invariant is enforced here rather than assumed.
    const CHUNK = 65536;
    for (let offset = 0; offset < out.length; offset += CHUNK) {
      getRandomValues.call(webcrypto, out.subarray(offset, Math.min(offset + CHUNK, out.length)));
    }
  };
}

/**
 * Produce `size` cryptographically secure random bytes.
 *
 * @param size   Number of bytes. Must be within [MIN_ENTROPY_BYTES, MAX_ENTROPY_BYTES].
 * @param source Test-only injection point. Never supplied by production code.
 */
export function randomBytes(
  size: number = DEFAULT_ENTROPY_BYTES,
  source?: RandomSource,
): Uint8Array {
  if (!Number.isInteger(size)) {
    throw new EntropyInsufficientError(size, MIN_ENTROPY_BYTES);
  }
  if (size < MIN_ENTROPY_BYTES) {
    throw new EntropyInsufficientError(size, MIN_ENTROPY_BYTES);
  }
  if (size > MAX_ENTROPY_BYTES) {
    throw new EntropyInsufficientError(size, MIN_ENTROPY_BYTES);
  }

  const out = new Uint8Array(size);
  (source ?? platformRandom())(out);
  return out;
}

/**
 * Generate wallet-grade entropy: 256 bits from the OS CSPRNG, no overrides.
 *
 * This is the only function wallet-generation code should call. It has no
 * `source` parameter *by design* — there is no syntactic way for a caller to
 * substitute a weak generator into wallet creation, not even accidentally.
 */
export function generateWalletEntropy(): Uint8Array {
  return randomBytes(DEFAULT_ENTROPY_BYTES);
}

/**
 * Overwrite a buffer holding secret material with zeros.
 *
 * ─── Honest limitations (this is not a security guarantee) ─────────────────
 * In a garbage-collected, JIT-compiled runtime this is best-effort only:
 *
 *   - The JS engine may have copied the buffer during GC compaction; we can
 *     only zero the copy we hold a reference to.
 *   - The OS may have paged the memory to swap or a hibernation file.
 *   - An optimising compiler is theoretically permitted to elide a write that
 *     is never read. (In practice V8 does not elide TypedArray stores, but
 *     "in practice" is not a proof.)
 *
 * We do it anyway because it shrinks the *window* during which a heap dump or
 * core dump contains live key material, and that is a real reduction in
 * exposure even though it is not elimination. Pretending otherwise would be
 * exactly the kind of security theatre this project exists to avoid.
 */
export function wipe(secret: Uint8Array): void {
  secret.fill(0);
}
